resilience4j:
  circuitbreaker:
    instances:
      api:
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: count_based
  retry:
    instances:
      api:
        max-attempts: 5
        wait-duration: 3s
  rate-limiter:
    instances:
      api:
        limit-for-period: 2
        limit-refresh-period: 1s
        timeout-duration: 1s
